### PR TITLE
Set the default SCOUT_DRIVER to 'null'.

### PR DESCRIPTION
**Pull request by DFurnes**
### What's this PR do?

This pull request sets the default `SCOUT_DRIVER` to `'null'`. This fixes an issue where we'd pass the _actual_ `null` value (from the empty value in `.env`) when trying to create a driver and it'd explode whenever the application tried to boot:

```
Type error: Too few arguments to function Illuminate\Support\Manager::createDriver(), 0 passed
```

### How should this be reviewed?

When running this application with a fresh `.env`, things should no longer error out.

### Any background context you want to provide?

This was a bug introduced in #1022.

### Relevant tickets

References [Pivotal #173252821](https://www.pivotaltracker.com/story/show/173252821).

### Checklist

- [ ] This PR has been added to the relevant Pivotal card.
- [ ] Documentation added for new features/changed endpoints.
- [ ] Added appropriate feature/unit tests.

### CODE REVIEW

**Comment by DFurnes** [comment]
> EDIT: Ohhh, or is it that it literally uses the empty `null` value from the unset .env variable and _not_ the default string?

Yeah, which surprised me! Since we had the variable defined in `.env` but empty, it wouldn't use the "fallback" default value from the `conifg/scout.php`, and instead just passes along that (literal) `null` value to the Manager class.

**Comment by mendelB** [comment]
> > EDIT: Ohhh, or is it that it literally uses the empty `null` value from the unset .env variable and _not_ the default string?
> 
> Yeah, which surprised me! Since we had the variable defined in `.env` but empty, it wouldn't use the "fallback" default value from the `conifg/scout.php`, and instead just passes along that (literal) `null` value to the Manager class.

Ah, jeepers. Good to know for the future!
